#program to develop a regression model on an existing dataset.

In [1]:
#importing diffrent libraries.

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
#loading boston dataset from the sklearn.datasets.
boston = load_boston()

In [3]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': 'C:\\Ananconda\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'}

In [8]:
#creating a dataframe of boston dataset.
bostondf = pd.DataFrame(boston.data, columns = boston.feature_names)

In [9]:
bostondf

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [10]:
target = pd.DataFrame(boston.target)

In [12]:
bostondf['MEDV'] = boston.target

In [15]:
#creating the same dataset using seed() function.
np.random.seed(2000)

In [16]:
#creating the training and test data set
train, test = train_test_split(bostondf, test_size = 0.3)

In [17]:
train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
392,11.57790,0.0,18.10,0.0,0.700,5.036,97.0,1.7700,24.0,666.0,20.2,396.90,25.68,9.7
144,2.77974,0.0,19.58,0.0,0.871,4.903,97.8,1.3459,5.0,403.0,14.7,396.90,29.29,11.8
311,0.79041,0.0,9.90,0.0,0.544,6.122,52.8,2.6403,4.0,304.0,18.4,396.90,5.98,22.1
266,0.78570,20.0,3.97,0.0,0.647,7.014,84.6,2.1329,5.0,264.0,13.0,384.07,14.79,30.7
153,2.14918,0.0,19.58,0.0,0.871,5.709,98.5,1.6232,5.0,403.0,14.7,261.95,15.79,19.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,0.01360,75.0,4.00,0.0,0.410,5.888,47.6,7.3197,3.0,469.0,21.1,396.90,14.80,18.9
461,3.69311,0.0,18.10,0.0,0.713,6.376,88.4,2.5671,24.0,666.0,20.2,391.43,14.65,17.7
206,0.22969,0.0,10.59,0.0,0.489,6.326,52.5,4.3549,4.0,277.0,18.6,394.87,10.97,24.4
328,0.06617,0.0,3.24,0.0,0.460,5.868,25.8,5.2146,4.0,430.0,16.9,382.44,9.97,19.3
438,13.67810,0.0,18.10,0.0,0.740,5.935,87.9,1.8206,24.0,666.0,20.2,68.95,34.02,8.4

In [19]:
test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
262,0.52014,20.0,3.97,0.0,0.6470,8.398,91.5,2.2885,5.0,264.0,13.0,386.86,5.91,48.8
440,22.05110,0.0,18.10,0.0,0.7400,5.818,92.4,1.8662,24.0,666.0,20.2,391.45,22.11,10.5
342,0.02498,0.0,1.89,0.0,0.5180,6.540,59.7,6.2669,1.0,422.0,15.9,389.96,8.65,16.5
347,0.01870,85.0,4.15,0.0,0.4290,6.516,27.7,8.5353,4.0,351.0,17.9,392.43,6.36,23.1
222,0.62356,0.0,6.20,1.0,0.5070,6.879,77.7,3.2721,8.0,307.0,17.4,390.39,9.93,27.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,8.26725,0.0,18.10,1.0,0.6680,5.875,89.6,1.1296,24.0,666.0,20.2,347.88,8.88,50.0
204,0.02009,95.0,2.68,0.0,0.4161,8.034,31.9,5.1180,4.0,224.0,14.7,390.55,2.88,50.0
131,1.19294,0.0,21.89,0.0,0.6240,6.326,97.7,2.2710,4.0,437.0,21.2,396.90,12.26,19.6
122,0.09299,0.0,25.65,0.0,0.5810,5.961,92.9,2.0869,2.0,188.0,19.1,378.09,17.93,20.5
33,1.15172,0.0,8.14,0.0,0.5380,5.701,95.0,3.7872,4.0,307.0,21.0,358.77,18.35,13.1

In [25]:
X_train = train.drop('MEDV', axis = 1)
Y_train = train.drop('MEDV', axis = 1)
X_test = test.drop('MEDV', axis = 1)
Y_test = test['MEDV']

In [27]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
262,0.52014,20.0,3.97,0.0,0.6470,8.398,91.5,2.2885,5.0,264.0,13.0,386.86,5.91
440,22.05110,0.0,18.10,0.0,0.7400,5.818,92.4,1.8662,24.0,666.0,20.2,391.45,22.11
342,0.02498,0.0,1.89,0.0,0.5180,6.540,59.7,6.2669,1.0,422.0,15.9,389.96,8.65
347,0.01870,85.0,4.15,0.0,0.4290,6.516,27.7,8.5353,4.0,351.0,17.9,392.43,6.36
222,0.62356,0.0,6.20,1.0,0.5070,6.879,77.7,3.2721,8.0,307.0,17.4,390.39,9.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,8.26725,0.0,18.10,1.0,0.6680,5.875,89.6,1.1296,24.0,666.0,20.2,347.88,8.88
204,0.02009,95.0,2.68,0.0,0.4161,8.034,31.9,5.1180,4.0,224.0,14.7,390.55,2.88
131,1.19294,0.0,21.89,0.0,0.6240,6.326,97.7,2.2710,4.0,437.0,21.2,396.90,12.26
122,0.09299,0.0,25.65,0.0,0.5810,5.961,92.9,2.0869,2.0,188.0,19.1,378.09,17.93
33,1.15172,0.0,8.14,0.0,0.5380,5.701,95.0,3.7872,4.0,307.0,21.0,358.77,18.35

In [28]:
#creating a linear regression model
model = linear_model.LinearRegression()

In [29]:
model

LinearRegression()

In [30]:
#train the model using the training sets
model.fit(X_train, Y_train)

LinearRegression()

In [31]:
#determining the accuracy of the training dataset
print('Accurecy of training datasets is : \n', model.score(X_train, Y_train))

Accurecy of training datasets is :
 1.0

In [32]:
#displaying equation coefficient
print('value of cofficients is: \n', model.coef_)

value of cofficients is:
 [[ 1.00000000e+00 -5.75519543e-16  1.11301476e-17  9.05412042e-18
   3.91803659e-15  7.11395478e-16 -2.45274154e-16 -8.50172618e-17
  -2.39130020e-16  6.71761679e-17 -2.09710807e-17  4.12222622e-18
  -1.26018842e-15]
 [-3.83175034e-15  1.00000000e+00 -9.59187519e-16  4.65223019e-15
  -4.64597887e-14 -4.29203234e-15  5.69174369e-16 -1.04730618e-16
  -7.96421909e-16 -1.86345460e-15  1.34507205e-16 -5.86610498e-15
  -1.19576478e-16]
 [ 1.25355537e-16 -7.62562058e-17  1.00000000e+00  1.30880297e-15
  -1.39665486e-14 -7.54133525e-16  8.66405302e-17 -9.48569371e-17
   6.07211726e-16  2.29095462e-16  1.76193312e-16  8.82403666e-16
   5.98832854e-16]
 [-2.68223569e-16  6.97499234e-17 -3.20235761e-16  1.00000000e+00
   7.95795834e-16  1.24345281e-18  2.59722560e-16  1.45201601e-16
   1.42702987e-19 -3.54569887e-17 -6.21534466e-17 -1.10225843e-16
  -5.96853122e-17]
 [ 3.39402065e-17 -4.03549139e-17 -2.05691032e-17 -4.95188681e-16
   1.00000000e+00 -4.18089441e-16 -7.65547064e-17  1.15883185e-16
  -9.55405529e-17  1.17915289e-17 -2.85286114e-18  1.54362008e-17
   6.43187042e-18]
 [ 1.44822559e-16  9.73556281e-17  4.29204169e-17  1.41565684e-15
  -1.04192086e-14  1.00000000e+00  1.16728337e-16  8.25750262e-18
  -7.69450349e-17 -1.23880787e-17 -1.46087009e-16 -5.03551696e-17
  -1.35936432e-16]
 [-3.53287244e-16 -9.58721788e-17  1.01391033e-16  1.85016876e-14
  -6.95578168e-14  8.03143134e-16  1.00000000e+00  3.99002560e-16
   1.79489800e-16  2.04731947e-15 -2.58985145e-16  6.96771180e-15
   2.07826593e-16]
 [ 6.68395720e-19  1.23116490e-17 -4.33149829e-16  8.80961006e-16
  -3.33062821e-15 -4.46835614e-16  2.97333286e-17  1.00000000e+00
  -3.88156174e-16 -1.07573699e-16  8.57292447e-16 -4.32223724e-16
   1.77735638e-17]
 [-4.28043622e-16 -2.68954352e-16  1.11995143e-15  6.18763871e-15
   1.31610259e-14  2.52088520e-15 -3.67715267e-16 -5.26880119e-18
   1.00000000e+00 -1.41044563e-17 -5.37570308e-17  4.08645207e-17
  -1.33937107e-16]
 [ 3.76926188e-15 -1.00584960e-15  6.16880960e-15 -8.66897703e-15
   2.05974451e-13  1.27572756e-14 -2.69730732e-16  7.35940792e-15
   7.91472107e-16  1.00000000e+00  9.17025571e-16 -5.03660952e-16
  -5.91553127e-16]
 [-3.08324301e-17 -5.76809893e-17  2.48794592e-16  4.84054949e-16
  -5.26372943e-15 -9.62975166e-18  5.51014035e-18  7.14556389e-16
  -7.23586468e-17  3.01094741e-17  1.00000000e+00  1.18742240e-16
  -1.36664180e-16]
 [ 2.63972118e-16  6.84033112e-16 -2.24247893e-15  2.15425714e-15
  -2.13691190e-14 -4.41803263e-15  7.09532499e-17 -2.51204389e-15
  -8.29342628e-16  2.48862219e-16 -6.59784708e-17  1.00000000e+00
   3.32320455e-16]
 [-1.54506293e-15 -2.27226022e-16  7.79881133e-16 -8.97653996e-15
   1.22669817e-14 -9.41591130e-16 -4.53980799e-16  8.07099386e-17
  -7.11595269e-16  3.21912751e-16 -3.40135502e-18  8.20948310e-16
   1.00000000e+00]]

In [33]:
#displaying equation intercept
print('value of intercept is : \n', model.intercept_)

value of intercept is :
 [ 1.55431223e-14  2.89013258e-12 -4.15667500e-13  4.08909018e-14
 -3.88578059e-15  2.75335310e-14 -3.32534000e-12  1.94955163e-13
 -1.77635684e-14  3.97903932e-13 -7.10542736e-14 -5.68434189e-14
 -3.80140364e-13]

In [34]:
#Predict the output from test set
predicted = model.predict(X_test)

In [41]:
predicted.shape

(152, 13)

In [38]:
#determining root mean squared error
from math import sqrt
rmselm = sqrt(mean_squared_error(Y_test, predicted))

ValueError: y_true and y_pred have different number of output (1!=13)